# Generated by Django 5.1.7 on 2025-03-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inwardqnty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='purchaseprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
