# Generated by Django 5.1.7 on 2025-03-22 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0002_products_inwardqnty_products_purchaseprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customername', models.CharField(max_length=200)),
                ('mobileno', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit mobile number.')])),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='mobile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zero.customer'),
        ),
        migrations.AddField(
            model_name='products',
            name='mobile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zero.customer'),
        ),
    ]
