# Generated by Django 5.1.7 on 2025-03-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0003_customer_invoice_mobile_products_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.CreateModel(
            name='InvoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoiceid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zero.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero.products')),
            ],
        ),
    ]
