# Generated by Django 5.1.7 on 2025-03-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0004_remove_invoice_product_remove_invoice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicelist',
            name='invoiceid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoicelist', to='zero.invoice'),
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseprice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('purchaseqnty', models.IntegerField(default=0)),
                ('purchasedate', models.DateTimeField(auto_now_add=True)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero.products')),
            ],
        ),
    ]
