# Generated by Django 5.1.7 on 2025-03-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0006_products_purchasedate_delete_purchaselist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='mobile',
        ),
    ]
