# Generated by Django 5.1.7 on 2025-03-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0007_remove_products_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('purchaseid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('purchaseprice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('purchaseqnty', models.IntegerField(default=0)),
                ('purchasedate', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero.products')),
            ],
        ),
    ]
