# Generated by Django 5.1.7 on 2025-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0008_purchaselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselist',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
